#!/usr/bin/python

# Written by Dr. Yuhang Wang for SI601
# Find the good businesses (4.5+ stars) in each category, ranked by stars
# Input : file generated by mr_cityfilter.py
# To run locally:  python mr_good_business_per_category.py a2businesses > good_business_per_category

from mrjob.job import MRJob
import json

class GoodBusiness(MRJob):

  def mapper(self, _, line):
    key, value = line.split('\t')
    data = json.loads(value)
    categories = data.get('categories', None)
    if categories:
      for c in categories:
        stars = data.get('stars', None)
        if stars != None:
          if stars >= 4.5:
            yield (c, (data['name'], stars))

  def reducer(self, category, valuegen):
    ranked_list = sorted(valuegen, key = lambda x: x[1], reverse = True)
    yield (category, ranked_list)


if __name__ == '__main__':
    GoodBusiness.run()